export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const SIGNUP = 'SIGNUP';

export const ADMIN_FETCH_EVENTS = 'ADMIN_FETCH_EVENTS';
export const ADMIN_FETCH_EVENT = 'ADMIN_FETCH_EVENT';
export const ADMIN_CREATE_EVENT = 'ADMIN_CREATE_EVENT';
export const ADMIN_DELETE_EVENT = 'ADMIN_DELETE_EVENT';
export const ADMIN_UPDATE_EVENT = 'ADMIN_UPDATE_EVENT';

export const ADMIN_FETCH_EVENT_SIGNUPS = 'ADMIN_FETCH_EVENT_SIGNUPS';

export const ADMIN_FETCH_LOCATIONS = 'ADMIN_FETCH_LOCATIONS';
export const ADMIN_CREATE_LOCATION = 'ADMIN_CREATE_LOCATION';